### ISSUE TITLE
Hodkin -> Hodgkin...

### ISSUE THREAD

**Issue by pgleeson** [EPFL-LCN/neuronaldynamics-exercises#1]
@flinz Looks good!

Ok to add this to OSB?

**Comment by flinz** [comment]
@pgleeson thanks for the typo.

Sure thing, feel free to add it.
The plan is to add more exercises soon, too.

**Comment by flinz** [comment]
Fixed typos, closing issue.

**Comment by pgleeson** [comment]
@flinz, have finally added the repo on OSB here: http://www.opensourcebrain.org/projects/neuronal-dynamics-book.

Feel free to sign up to OSB and I'll add you to that project (so you can edit the text/links/metadata).

Have also added this as a link here: http://www.opensourcebrain.org/docs/Help/Background_Information#Introduction_to_Computational_Neuroscience

**Comment by flinz** [comment]
@pgleeson yep, all worked. thanks for adding it!
