### ISSUE TITLE
for help

### ISSUE THREAD

**Issue by scitao** [EPFL-LCN/neuronaldynamics-exercises#2]
Where can we Download the required files (such as HH.py, etc)?

**Comment by flinz** [comment]
@scitao they are in each of the subdirectories. 
To run them, you have to be inside the folder, e.g. for the HH.py file you mentioned:

```bash
 % cd hodkin-huxley
 % ipython
Python 2.7.10 (default, Nov  3 2015, 19:30:28)
Type "copyright", "credits" or "license" for more information.

In [1]: import HH
In [2]: HH.HH_Ramp()
```
