### ISSUE TITLE
brian or brian2?

### ISSUE THREAD

**Issue by peppe92** [EPFL-LCN/neuronaldynamics-exercises#3]
It looks like these python codes  import  brian modules instead of installed brian2 ones , if this might be easily fixed,  i don't know how to solve for  brian.library.ionic_currents import
Any advice?

**Comment by flinz** [comment]
The master branch is all written for brian. However, we are currently rewriting and converting all examples to brian2, as well as adding additional ones. This is available on the [brian2 branch](https://github.com/EPFL-LCN/neuronaldynamics-exercises/tree/brian2).

**Comment by peppe92** [comment]
thank you
