### ISSUE TITLE
Units in questions 2.2

### ISSUE THREAD

**Issue by GillesBaud** [EPFL-LCN/neuronaldynamics-exercises#4]
Units in questions 2.2.1 and 2.2.2 in page [http://neuronaldynamics-exercises.readthedocs.org/en/latest/exercises/leaky-integrate-and-fire.html]([http://neuronaldynamics-exercises.readthedocs.org/en/latest/exercises/leaky-integrate-and-fire.html]) should be kHz.

**Comment by flinz** [comment]
Thanks for reporting! Corrected with https://github.com/EPFL-LCN/neuronaldynamics-exercises/commit/d012aa5e8fb86e540c918a3d3678ccabe23e1239.
